# Generated by Django 3.1 on 2020-12-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_auto_20201224_1140"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="date_of_birth",
            field=models.DateTimeField(),
        ),
    ]
