# Generated by Django 3.1 on 2020-12-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20201224_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="date_of_birth",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
